services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siram-sdmo-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - siram-network
    depends_on:
      - db

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: siram-sdmo-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - siram-network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: siram-sdmo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_absensi_bkn
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - siram-network

networks:
  siram-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
